# SPDX-License-Identifier: Apache-2.0

name: Functional tests
description: Run functional tests for MLKEM-C_AArch64

inputs:
  nix-shell:
    description: Run in the specified Nix environment if exists
    default: "ci"
  custom_shell:
    description: The shell to use. Only relevant if no nix-shell specified
    default: "bash"
  cflags:
    description: CFLAGS to pass to compilation
    default: ""
  mode:
    description: For auto-determining the default cross-prefix (e.g. native | cross )
    default: "native"
  opt:
    description: opt flag to pass to test script
    default: "true"
  func:
    description: Determine whether to run functional test or not
    default: "true"
  kat:
    description: Determine whether to run kat test or not
    default: "true"
  nistkat:
    description: Determine whether to run nistkat test or not
    default: "true"
runs:
  using: composite
  steps:
      - name: Preprocess
        shell: bash
        run: |
          arch=$(uname -m)
          if [[ $arch == "x86_64" ]]; then
              _cross_prefix="aarch64-unknown-linux-gnu-"
          elif [[ $arch == "aarch64" ]]; then
              _cross_prefix="x86_64-unknown-linux-gnu-"
          fi

          if [[ ${{ inputs.mode }} == "cross" ]]; then
              cross_prefix="$_cross_prefix"
          fi
          echo _CROSS_PREFIX="$_cross_prefix" >> $GITHUB_ENV # this is for printing summary only, which doesn't depend on inputs.mode
          echo CROSS_PREFIX="$cross_prefix" >> $GITHUB_ENV
          echo OPT="${{ inputs.opt == 'true' && 'opt' || 'no-opt' }}" >> $GITHUB_ENV

          echo FUNC="${{ inputs.func == 'true' && 'func' || 'no-func' }}" >> $GITHUB_ENV
          echo KAT="${{ inputs.kat == 'true' && 'kat' || 'no-kat' }}" >> $GITHUB_ENV
          echo NISTKAT="${{ inputs.nistkat == 'true' && 'nistkat' || 'no-nistkat' }}" >> $GITHUB_ENV
      - name: Setup nix
        uses: ./.github/actions/setup-shell
        with:
          nix-shell: ${{ inputs.nix-shell }}
          custom_shell: ${{ inputs.custom_shell }}
          script: |
            # only summary on the first time
            if [[ "${{ env.SHELL }}" == '' ]]; then
              ARCH=$(uname -m)
            cat >> $GITHUB_STEP_SUMMARY <<-EOF
              ## Setup
              Architecture: $ARCH
              - $(uname -a)
              - $(nix --version)
              - $(bash --version | grep -m1 "")
              - $(gcc --version | grep -m1 "")
            EOF

              # no cross gcc in darwin
              if [[ $(uname -s) != "Darwin" ]]; then
                echo "- $(${{ env._CROSS_PREFIX }}gcc --version | grep -m1 '')" >> $GITHUB_STEP_SUMMARY
              fi
            fi

      - name: Compile ${{ inputs.mode }} ${{ env.OPT }} tests (${{ env.FUNC }}, ${{ env.KAT }}, ${{ env.NISTKAT }})
        shell: ${{ env.SHELL }}
        run: |
          tests all  --cross-prefix="${{ env.CROSS_PREFIX }}" --cflags="${{ inputs.cflags }}" --${{ env.OPT }} --${{ env.FUNC }} --${{ env.KAT }} --${{ env.NISTKAT }} --compile --no-run -v
      - name: Run ${{ inputs.mode }} ${{ env.OPT }} tests (${{ env.FUNC }}, ${{ env.KAT }}, ${{ env.NISTKAT }})
        shell: ${{ env.SHELL }}
        run: |
          tests all  --cross-prefix="${{ env.CROSS_PREFIX }}" --cflags="${{ inputs.cflags }}" --${{ env.OPT }} --${{ env.FUNC }} --${{ env.KAT }} --${{ env.NISTKAT }} --no-compile --run -v
      - name: Post ${{ inputs.mode }} Tests
        shell: ${{ env.SHELL }}
        if: success() || failure()
        run: |
          make clean
