#!/usr/bin/env python3
# Copyright (c) 2024 The mlkem-native project authors
# SPDX-License-Identifier: Apache-2.0

# This scripts runs nm on the object files (excluding test objects) and checks that all exported
# symbols are properly namespaced.
# It assumes that object files are present under test/build/mlkem{512,768,1024} and
# test/build/fips202.

# The checked namespaces are
# PQCP_MLKEM_NATIVE_FIPS202_ for FIPS202 code
# PQCP_MLKEM_NATIVE_MLKEM512_ for MLKEM512 code
# PQCP_MLKEM_NATIVE_MLKEM768_ for MLKEM768 code
# PQCP_MLKEM_NATIVE_MLKEM1024_ for MLKEM1024 code

import subprocess
import os


def check_file(file_path, namespaces):
    if file_path.endswith("debug.c.o"):
        print("skipping namespacing: {}".format(file_path))
        return
    print("checking namespacing: {}".format(file_path))
    command = ["nm", "-g", file_path]

    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

    result = result.stdout.decode("utf-8")
    lines = result.strip().split("\n")
    symbols = []
    for line in lines:
        if line.startswith("00"):
            symbols.append(line)

    def is_namespaced(symbol):
        for namespace in namespaces:
            if symbol.startswith(namespace) or symbol.startswith("_" + namespace):
                return True
        return False

    non_namespaced = []
    for symbolstr in symbols:
        *_, symtype, symbol = symbolstr.split()
        if symtype in "TDRS":
            if is_namespaced(symbol) is False:
                non_namespaced.append(symbol)

    if len(non_namespaced) > 0:
        print("Missing namespace literal from {}".format(namespaces))
        for symbol in non_namespaced:
            print("\tsymbol: {}".format(symbol))
    assert not non_namespaced, "Literals with missing namespaces"


def check_folder(folder, namespace):
    checked = 0
    # recursively go through folder and check all object files
    for root, dirnames, filenames in os.walk(folder):
        for filename in filenames:
            if filename.endswith(".o"):
                check_file(os.path.join(root, filename), namespace)
                checked += 1
    print("Checked {} files".format(checked))
    assert checked > 0


def list_mlkem_namespaces(lvl):
    return [
        f"PQCP_MLKEM_NATIVE_MLKEM{lvl}_C",
        f"PQCP_MLKEM_NATIVE_MLKEM{lvl}_AARCH64",
        f"PQCP_MLKEM_NATIVE_MLKEM{lvl}_X86_64",
    ]


def list_fips202_namespaces():
    return [
        f"PQCP_MLKEM_NATIVE_FIPS202_C",
        f"PQCP_MLKEM_NATIVE_FIPS202_AARCH64",
        f"PQCP_MLKEM_NATIVE_FIPS202_X86_64",
    ]


def run():
    check_folder("test/build/mlkem512/mlkem", list_mlkem_namespaces(512))
    check_folder("test/build/mlkem768/mlkem", list_mlkem_namespaces(768))
    check_folder("test/build/mlkem1024/mlkem", list_mlkem_namespaces(1024))
    check_folder("test/build/mlkem/fips202", list_fips202_namespaces())


if __name__ == "__main__":
    run()
