# SPDX-License-Identifier: Apache-2.0

name: CBMC
description: Run CBMC proofs for MLKEM-C_AArch64

inputs:
  nix-shell:
    description: Run in the specified Nix environment if exists
    default: "ci-cbmc"
  nix-cache:
    description: Determine whether to enable nix cache
    default: 'true'
  nix-verbose:
    description: Determine wether to suppress nix log or not
    default: 'false'
  custom_shell:
    description: The shell to use. Only relevant if use-nix is 'false'
    default: "bash"
  gh_token:
    description: Github access token to use
    required: true
runs:
  using: composite
  steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-shell
        with:
          nix-shell: ${{ inputs.nix-shell }}
          nix-cache: ${{ inputs.nix-cache }}
          nix-verbose: ${{ inputs.nix-verbose }}
          gh_token: ${{ inputs.gh_token }}
          custom_shell: ${{ inputs.custom_shell }}
          script: |
            cat >> $GITHUB_STEP_SUMMARY << EOF
              ## Setup
              Architecture: $(uname -m)
              - $(nix --version)
              - $(cbmc --version)
              - litani Version $(litani --version)
              - Cadical Version $(cadical --version)
              - $(bash --version | grep -m1 "")
            EOF
      - name: Run CBMC proofs
        shell: ${{ env.SHELL }}
        run: |
          cd cbmc/proofs;
          echo "::group::cbmc"
          MLKEM_K=2 ./run-cbmc-proofs.py --summarize;
          MLKEM_K=3 ./run-cbmc-proofs.py --summarize;
          MLKEM_K=4 ./run-cbmc-proofs.py --summarize;
          echo "::endgroup::"
