#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

import os
import sys
import re

sys.path.append(f"{os.path.join(os.path.dirname(__file__), 'lib')}")
from mlkem_test import *
from util import (
    path,
    config_logger,
)

opts = Options()
opts.compile = False

config_logger(opts.verbose)

build_config = path("test/build/config.mk")
acvp_test_data = path("test/acvp_data/")

if not os.path.isfile(build_config):
    logging.error(f"{build_config} not found")
    exit(1)


def get_opt() -> bool:
    with open(build_config, "r") as file:
        for line in file:
            # Use regex to match lines in the format "OPT := value"
            match = re.match(r"^OPT\s*:=\s*(.*)$", line)
            if match:
                value = match.group(1).strip()
                return value == "1"
        logging.error(f"OPT is not defined in {build_config}")
        exit(1)


opts.opt = "opt" if get_opt() else "no_opt"

Tests(opts).acvp("test/acvp_data/")
