#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

# This script executes a binary file, captures its output, then generates and compares its SHA-256 hash with a provided one.

if [[ "$OSTYPE" == "darwin"* ]]; then
    output_hash=$(./$1 | sha2 -256 | awk '{ print $4 }')
else
    output_hash=$(./$1 | sha256sum | awk '{ print $1 }')
fi


if [[ ${output_hash} == "${2}" ]]; then
  echo "${1#*_} Hashes match."
  exit 0
else
  echo "${1#*_} Hashes do not match: ${output_hash} vs ${2}"
  exit 1
fi
