#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0

import platform
import sys
import os
import subprocess
import logging
import click
import hashlib
from functools import reduce
from enum import Enum


def config_logger(verbose):
    if verbose:
        logging.basicConfig(format="%(levelname)-5s > %(message)s", level=logging.DEBUG)
    else:
        logging.basicConfig(format="%(levelname)-5s > %(message)s", level=logging.INFO)


def sha256sum(result):
    m = hashlib.sha256()
    m.update(result)
    return m.hexdigest()


class TEST_TYPES(Enum):
    MLKEM = 1
    BENCH = 2
    NISTKAT = 3
    KAT = 4

    def __str__(self):
        return self.name.lower()

    def desc(self):
        match self:
            case TEST_TYPES.MLKEM:
                return "Functional Test"
            case TEST_TYPES.BENCH:
                return "Benchmark"
            case TEST_TYPES.NISTKAT:
                return "Nistkat Test"
            case TEST_TYPES.KAT:
                return "Kat Test"

    def bin(self):
        match self:
            case TEST_TYPES.MLKEM:
                return "test_kyber"
            case TEST_TYPES.BENCH:
                return "bench_kyber"
            case TEST_TYPES.NISTKAT:
                return "gen_NISTKAT"
            case TEST_TYPES.KAT:
                return "gen_KAT"

    def bin_path(self, scheme):
        return f"test/build/{scheme.name.lower()}/bin/{self.bin()}{scheme.suffix()}"


class SCHEME(Enum):
    MLKEM512 = 1
    MLKEM768 = 2
    MLKEM1024 = 3

    def __str__(self):
        return self.name

    def suffix(self):
        return self.name.removeprefix("MLKEM")


def base_compile(
    test,
    verbose,
    cross_prefix,
    extra_make_envs={},
    extra_make_args=[],
):
    """compile or cross compile with some extra environment variables and makefile arguments"""

    def dict2str(dict):
        s = ""
        for k, v in dict.items():
            s += f"{k}={v} "
        return s

    logging.debug(f"Compiling {test}...")
    args = [
        "make",
        f"CROSS_PREFIX={cross_prefix}",
        f"{test}",
    ] + extra_make_args

    logging.info(dict2str(extra_make_envs) + " ".join(args))

    p = subprocess.run(
        args,
        stdout=subprocess.DEVNULL if not verbose else None,
        env=os.environ.copy() | extra_make_envs,
    )

    if p.returncode != 0:
        logging.error(f"make failed: {p.returncode}")
        sys.exit(1)


def base_run(
    bin,
    force_qemu,
    verbose,
    run_as_root=False,
    exec_wrapper=None,
):
    """Run the binary in all different ways"""
    cmd = [f"./{bin}"]
    if force_qemu or (platform.system() == "Linux" and platform.machine() == "x86_64"):
        logging.info(f"Emulating {bin} with QEMU")
        cmd = ["qemu-aarch64"] + cmd

    if run_as_root:
        logging.info(
            f"Running {bin} as root -- you may need to enter your root password."
        )
        cmd = ["sudo"] + cmd

    if exec_wrapper:
        logging.info(f"Running {bin} with customized wrapper.")
        exec_wrapper = exec_wrapper.split(" ")
        cmd = exec_wrapper + cmd

    logging.info(" ".join(cmd))
    result = subprocess.run(
        cmd,
        capture_output=True,
        universal_newlines=False,
    )

    if result.returncode != 0:
        logging.error(
            f"Running '{cmd}' failed: {result.returncode} {result.stderr.decode()}"
        )
        sys.exit(1)

    return result.stdout


def parse_meta(scheme, field):
    result = subprocess.run(
        [
            "yq",
            "-r",
            "--arg",
            "scheme",
            scheme.name.lower(),
            f'.implementations.[] | select(.name == $scheme) | ."{field}"',
            "./META.yml",
        ],
        capture_output=True,
        encoding="utf-8",
        universal_newlines=False,
    )
    return result.stdout.strip()


def test_schemes(
    test,
    actual_proc,
    expect_proc,
    process_result,
    force_qemu,
    verbose,
    cross_prefix,
    run_as_root=False,
    exec_wrapper=None,
    extra_make_envs={},
    extra_make_args=[],
):
    """
    :param process_result: process result and return summary
    """
    logging.info(f"{test.desc()}")

    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    summary = f"## {test.desc()}\n"

    fail = False
    results = {}
    base_compile(test, verbose, cross_prefix, extra_make_envs, extra_make_args)
    for scheme in SCHEME:
        result = base_run(
            test.bin_path(scheme),
            force_qemu,
            verbose,
            run_as_root,
            exec_wrapper,
        )
        results[scheme] = result

        actual = actual_proc(result)
        expect = expect_proc(scheme)

        f = actual != expect
        s = process_result(f, scheme, result, expect, actual)
        summary += s
        fail = fail or f

    if summary_file is not None:
        with open(summary_file, "a") as f:
            print(summary, file=f)

    if fail:
        sys.exit(1)

    return results


def process_test(fail, scheme, result, expect, actual):
    if fail:
        logging.error(f"{scheme} failed, expecting {expect}, but getting {actual}")
        summary = f":x: {scheme}, expecting {expect}, but getting {actual}\n"
    else:
        logging.info(f"{scheme} passed")
        summary = f":white_check_mark: {scheme}\n"

    return summary


def process_bench(fail, scheme, result, expect, actual):
    logging.info(f"{scheme}")
    logging.info(f"\n{result.decode()}")

    summary = f"{scheme}\n{result.decode()}\n"

    return summary


def validate_force_qemu(ctx, _, v):
    if platform.system() == "Darwin" and v:
        config_logger(False)
        logging.error("qemu-aarch64 is not supported on Darwin")
        ctx.exit(1)


def process_make_envs(cflags, arch_flags):
    return ({"CFLAGS": f"{cflags}"} if cflags is not None else {}) | (
        {"ARCH_FLAGS": f"{arch_flags}"} if arch_flags is not None else {}
    )


_shared_options = [
    click.option(
        "--force-qemu",
        is_flag=True,
        show_default=True,
        default=False,
        type=bool,
        hidden=platform.system() == "Darwin",
        callback=validate_force_qemu,
        is_eager=True,
        help="Force to emulate with QEMU (not supported on macOS)",
    ),
    click.option(
        "-v",
        "--verbose",
        is_flag=True,
        show_default=True,
        default=False,
        type=bool,
        help="Show verbose output or not",
    ),
    click.option(
        "-cp",
        "--cross-prefix",
        default="aarch64-unknown-linux-gnu-" if platform.machine() == "x86_64" else " ",
        show_default=True,
        hidden=platform.machine() != "x86_64",
        nargs=1,
        help="Cross prefix for compilation on non-aarch64 machines",
    ),
    click.option(
        "--cflags",
        nargs=1,
        help="Extra cflags to passed in (e.g. '-mcpu=cortex-a72')",
    ),
    click.option(
        "--arch-flags",
        nargs=1,
        help="Extra arch flags to passed in (e.g. '-march=armv8')",
    ),
    click.option(
        "--opt",
        type=bool,
        show_default=True,
        default=True,
        help="Choose whether to enable assembly optimizations (if present)",
    ),
]


def add_options(options):
    return lambda func: reduce(lambda f, o: o(f), reversed(options), func)


@click.command(
    short_help="Run the functional tests for all parameter sets",
    context_settings={"show_default": True},
)
@add_options(_shared_options)
def func(force_qemu, verbose, cross_prefix, cflags, arch_flags, opt):
    config_logger(verbose)

    def expect(scheme):
        sk_bytes = parse_meta(scheme, "length-secret-key")
        pk_bytes = parse_meta(scheme, "length-public-key")
        ct_bytes = parse_meta(scheme, "length-ciphertext")

        return (
            f"CRYPTO_SECRETKEYBYTES:  {sk_bytes}\n"
            + f"CRYPTO_PUBLICKEYBYTES:  {pk_bytes}\n"
            + f"CRYPTO_CIPHERTEXTBYTES: {ct_bytes}\n"
        )

    test_schemes(
        TEST_TYPES.MLKEM,
        lambda result: str(result, encoding="utf-8"),
        expect,
        process_test,
        force_qemu,
        verbose,
        cross_prefix,
        extra_make_envs=process_make_envs(cflags, arch_flags),
        extra_make_args=[f"OPT={int(opt)}"],
    )


@click.command(
    short_help="Run the nistkat tests for all parameter sets",
    context_settings={"show_default": True},
)
@add_options(_shared_options)
def nistkat(force_qemu, verbose, cross_prefix, cflags, arch_flags, opt):
    config_logger(verbose)

    test_schemes(
        TEST_TYPES.NISTKAT,
        sha256sum,
        lambda scheme: parse_meta(scheme, "nistkat-sha256"),
        process_test,
        force_qemu,
        verbose,
        cross_prefix,
        extra_make_envs=process_make_envs(cflags, arch_flags),
        extra_make_args=[f"OPT={int(opt)}"],
    )


@click.command(
    short_help="Run the kat tests for all parameter sets",
    context_settings={"show_default": True},
)
@add_options(_shared_options)
def kat(force_qemu, verbose, cross_prefix, cflags, arch_flags, opt):
    config_logger(verbose)

    test_schemes(
        TEST_TYPES.KAT,
        sha256sum,
        lambda scheme: parse_meta(scheme, "kat-sha256"),
        process_test,
        force_qemu,
        verbose,
        cross_prefix,
        extra_make_envs=process_make_envs(cflags, arch_flags),
        extra_make_args=[f"OPT={int(opt)}"],
    )


@click.command(
    short_help="Run the benchmarks for all parameter sets",
    context_settings={"show_default": True},
)
@add_options(_shared_options)
@click.option(
    "-c",
    "--cycles",
    nargs=1,
    type=click.Choice(["NO", "PMU", "PERF", "M1"]),
    show_default=True,
    default="NO",
    help="Method for counting clock cycles. PMU requires (user-space) access to the Arm Performance Monitor Unit (PMU). PERF requires a kernel with perf support. M1 only works on Apple silicon.",
)
@click.option(
    "-o",
    "--output",
    nargs=1,
    help="Path to output file in json format",
)
@click.option(
    "-r",
    "--run-as-root",
    is_flag=True,
    show_default=True,
    default=False,
    type=bool,
    help="Benchmarking binary is run with sudo.",
)
@click.option(
    "-w",
    "--exec-wrapper",
    help="Run the benchmark binary with the user-customized wrapper.",
)
@click.option(
    "-t",
    "--mac-taskpolicy",
    nargs=1,
    type=click.Choice(["utility", "background", "maintenance"]),
    hidden=platform.system() != "Darwin",
    show_default=True,
    default=None,
    help="Run the program using the specified QoS clamp. Applies to MacOS only. Setting this flag to 'background' guarantees running on E-cores. This is an abbreviation of --exec-wrapper 'taskpolicy -c {mac_taskpolicy}'.",
)
def bench(
    force_qemu,
    verbose,
    cycles,
    cross_prefix,
    cflags,
    arch_flags,
    opt,
    output,
    run_as_root,
    exec_wrapper,
    mac_taskpolicy,
):
    config_logger(verbose)

    if mac_taskpolicy:
        if exec_wrapper:
            logging.error(f"cannot set both --mac-taskpolicy and --exec-wrapper")
            sys.exit(1)
        else:
            exec_wrapper = f"taskpolicy -c {mac_taskpolicy}"

    results = test_schemes(
        TEST_TYPES.BENCH,
        lambda _: True,
        lambda _: True,
        process_bench,
        force_qemu,
        verbose,
        cross_prefix,
        run_as_root,
        exec_wrapper,
        extra_make_envs=process_make_envs(cflags, arch_flags),
        extra_make_args=[
            f"CYCLES={cycles}",
            f"OPT={int(opt)}",
        ],
    )

    if output:
        import json

        with open(output, "w") as f:
            v = []
            for scheme in results:
                schemeStr = str(scheme)
                r = results[scheme]

                # The first 3 lines of the output are expected to be
                # keypair cycles=X
                # encaps cycles=X
                # decaps cycles=X

                lines = [
                    line.decode() for line in r.splitlines() if "=" in line.decode()
                ]

                d = {k: int(v) for k, v in (l.split("=") for l in lines)}
                for primitive in ["keypair", "encaps", "decaps"]:
                    v.append(
                        {
                            "name": f"{schemeStr} {primitive}",
                            "unit": "cycles",
                            "value": d[f"{primitive} cycles"],
                        }
                    )
            f.write(json.dumps(v))


@click.group(invoke_without_command=True)
def cli():
    pass


cli.add_command(func)
cli.add_command(nistkat)
cli.add_command(kat)
cli.add_command(bench)

if __name__ == "__main__":
    cli()
