# SPDX-License-Identifier: Apache-2.0

name: Lint
description: Lint MLKEM-C_AArch64

inputs:
  nix-shell:
    description: Run in the specified Nix environment if exists
    default: "ci-linter"
  custom_shell:
    description: The shell to use. Only relevant if no nix-shell specified
    default: "bash"
  cross-prefix:
    description: Binary prefix for cross compilation
    default: ""
runs:
  using: composite
  steps:
      - uses: ./.github/actions/setup-shell
        with:
          nix-shell: ${{ inputs.nix-shell }}
          custom_shell: ${{ inputs.custom_shell }}
          script: |
            cat >> $GITHUB_STEP_SUMMARY << EOF
              ## Setup
              Architecture: $(uname -m)
              - $(uname -a)
              - $(nix --version)
              - $(astyle --version)
              - $(${{ matrix.target.cross-prefix }}gcc --version | grep -m1 "")
              - $(bash --version | grep -m1 "")
            EOF
      - name: Run linter
        shell: ${{ env.SHELL }}
        run: |
          echo "## Lint & Checks" >> $GITHUB_STEP_SUMMARY
          lint
