# SPDX-License-Identifier: Apache-2.0

name: Lint
description: Lint MLKEM-C_AArch64

inputs:
  nix-shell:
    description: Run in the specified Nix environment if exists
    default: "ci-linter"
  custom_shell:
    description: The shell to use. Only relevant if no nix-shell specified
    default: "bash"
  cross-prefix:
    description: Binary prefix for cross compilation
    default: ""
runs:
  using: composite
  steps:
      - name: Setup nix
        if: ${{ inputs.nix-shell != '' }}
        uses: ./.github/actions/setup-nix
        with:
          devShell: ${{ inputs.nix-shell }}
          script: |
            cat >> $GITHUB_STEP_SUMMARY << EOF
              ## Setup
              Architecture: $(uname -m)
              - $(uname -a)
              - $(nix --version)
              - $(astyle --version)
              - $(${{ matrix.target.cross-prefix }}gcc --version | grep -m1 "")
              - $(bash --version | grep -m1 "")
            EOF
      - name: Set shell
        shell: bash
        run: echo SHELL="${{ inputs.nix-shell != '' && 'nix develop .#${{ inputs.nix-shell }} -c bash -e {0}' || inputs.custom_shell }}" >> $GITHUB_ENV
      - name: Run linter
        shell: ${{ env.SHELL }}
        run: |
          echo "## Lint & Checks" >> $GITHUB_STEP_SUMMARY
          lint
