# SPDX-License-Identifier: Apache-2.0

name: bench-ec2-any
on:
  workflow_dispatch:
    inputs:
      name:
        description: Alternative name of instance
        default: Graviton2
      ec2_instance_type:
        description: Type if EC2 instance to benchmark on
        default: t4g.small
      ec2_ami_id:
        description: AMI ID
        default: ami-096ea6a12ea24a797
      cflags:
        description: Custom CFLAGS for compilation
        default:
      archflags:
        description: Custom ARCH flags for compilation
        default: -mcpu=cortex-a76 -march=armv8.2-a
      store_results:
        description: Indicates if results should be pushed to github pages
        default: false
      always_terminate:
        description: Indicates if EC2 instance should always be terminated
        default: true
      bench_extra_args:
        description: Additional command line to be appended to `tests bench` script
        default: ''
jobs:
  bench-ec2-any:
    name: Ad-hoc benchmark on $${{ github.event.inputs.ec2_instance_type }}
    uses: ./.github/workflows/bench_ec2_reusable.yml
    with:
      ec2_instance_type: ${{ github.event.inputs.ec2_instance_type }}
      ec2_ami_id: ${{ github.event.inputs.ec2_ami_id }}
      cflags: ${{ github.event.inputs.cflags }}
      archflags: ${{ github.event.inputs.archflags }}
      name: ${{ github.event.inputs.name }}
      store_results: ${{ github.event.inputs.store_results }}
      always_terminate: ${{ github.event.inputs.always_terminate }}
      bench_extra_args: ${{ github.event.inputs.bench_extra_args }}
    secrets: inherit
