# SPDX-License-Identifier: Apache-2.0

name: Bench EC2
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ "labeled" ]
jobs:
  bench-gv2:
    name: Graviton2 ${{ matrix.opt.name }}
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        opt:
          - name: opt
            value: true
          - name: non-opt
            value: false
    uses: ./.github/workflows/bench_ec2_reusable.yml
    if: github.repository_owner == 'pq-code-package' && (github.event.label.name == 'benchmark' || github.ref == 'refs/heads/main')
    with:
      ec2_instance_type: t4g.small
      ec2_ami: ubuntu-latest (aarch64)
      archflags: -mcpu=cortex-a76 -march=armv8.2-a
      cflags: -DFORCE_AARCH64
      opt: ${{ matrix.opt.value }}
      store_results: true
      name: Graviton2
    secrets: inherit
  bench-gv3:
    name: Graviton3 ${{ matrix.opt.name }}
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      fail-fast: false
      matrix:
        opt:
          - name: opt
            value: true
          - name: non-opt
            value: false
    uses: ./.github/workflows/bench_ec2_reusable.yml
    if: github.repository_owner == 'pq-code-package' && (github.event.label.name == 'benchmark' || github.ref == 'refs/heads/main')
    with:
      ec2_instance_type: c7g.medium
      ec2_ami: ubuntu-latest (aarch64)
      archflags: -mcpu=neoverse-v1 -march=armv8.4-a
      cflags: -DFORCE_AARCH64
      opt: ${{ matrix.opt.value }}
      store_results: true
      name: Graviton3
    secrets: inherit
